### ISSUE TITLE
Confluence login stopped working today

### ISSUE THREAD

**Issue by levydev** [pycontribs/confluence#11]
I have been using :
conf = Confluence(url='https://aaasccp.atlassian.net/wiki', username=JIRA_USER,password=JIRA_PSWD)

My last successful run was Monday May 8.   When running it today I receive the following error:
    raise Fault(**self._stack[0])
xmlrpclib.Fault: <Fault 0: 'java.lang.Exception: java.lang.UnsupportedOperationException: The idplat does not support authenticateViaEmail, please use authenticateViaEmailWithHostname instead.'>

P

**Comment by paulwicking** [comment]
This seems to be due to a change that requires user names to include the host name ( `@example.com` ) part of an email address.

See also: 
https://bobswift.atlassian.net/browse/CSOAP-768
https://bobswift.atlassian.net/wiki/display/ACLI/Release+notes+6.6
