### ISSUE TITLE
Cloud api vs Server Api

### ISSUE THREAD

**Issue by JGONGSQ** [pycontribs/confluence#12]
Just trying to ask anyone who knows how to set the theme to a space with REST api, which is only available in Cloud api, but not in Server api. If anyone knows how to set the space theme with Server api, please let me know. 

Thank you !

**Comment by paulwicking** [comment]
Space themes cannot be set using the REST API on server installations.
Refer to the REST documentation for Confluence here: 
https://docs.atlassian.com/atlassian-confluence/REST/latest-server/

Alternatively, open a feature request for this with Atlassian.
