### ISSUE TITLE
SSL validation issues

### ISSUE THREAD

**Issue by devkmsg** [pycontribs/confluence#24]
I'm running into issues connecting to my Confluence server because it has a cert that is not in the normal cert chain.  I don't want to turn all SSL validation off (`ssl._create_default_https_context = ssl._create_unverified_context`).

Would you accept a PR that would allow a `context` to be passed into `xmlrpclib.ServerProxy`?
  From the [docs](https://docs.python.org/2/library/xmlrpclib.html#xmlrpclib.ServerProxy
):
```
context may be ssl.SSLContext and configures the SSL settings of the underlying HTTPS connection.
```

**Comment by devkmsg** [comment]
I went ahead and did this work.  If it's of interest, it can found in #25.

**Comment by paulwicking** [comment]
Thanks, @devkmsg ! I've merged your contribution, closing this issue.
