### ISSUE TITLE
Forgive my stupidity

### ISSUE THREAD

**Issue by Swiftkilla** [pycontribs/confluence#26]
I really need some instructions to get the setup sorted for a Windows development environment.

Creating an arbitrary file in my home directory doesn't seem like a normal way to configure a Python API wrapper and certainly wouldn't contain the correct commands e.g. EXPORT is not a batch command.

**Comment by paulwicking** [comment]
Having issues getting this up and running in a Windows environment is a valid cause for raising an issue, thank you for reporting this @Swiftkilla. At the very least, the documentation might need some work. I'll need to set up a Windows machine myself to explore it further, which might take a few days to get around to if I'm honest. In the meanwhile, you can try replacing `EXPORT` with `SET` (the Windows equivalent). The .ini file is there to avoid exposing usernames/passwords, as they are (normally) required for connecting to a Confluence server, even with the API.

**Comment by Swiftkilla** [comment]
Hey,
Many thanks for your reply.
If you could let me know how your setup goes and any problems you encounter, then we could hopefully get a solution together so that others who may want to use this in the same way as me would be enabled to.
I would love to use the wrapper and I do have several Linux environments available, however, for the purpose of the solution, I require it to be Windows based.
Thanks in advance.

**Comment by paulwicking** [comment]
Sorry for the late reply, @Swiftkilla, but life etc. came in the way.

I've finally come around to set up a Windows VM to play around with the module and have to admit I am uncertain what it is you've run into, exactly. Note that if you're on Python 3.6+, the module is not installable with pip but must be used from source in the development branch here on github.

When it comes to the file in your home directory or path, it is a configuration file that holds the host, username and password to connect to your Confluence instance. The module looks for this file in the current working directory and the logged in user's home directory. The purpose is to avoid putting this information inside the script that depends on the module (security best practice).

If you've already figured out what you were stuck with in the first place (and I hope you have :) ), feel free to close this issue. Any information about how you got stuck and what you did to overcome it can be valuable in further development of the module.

Also, any contribution is more than welcome!
