### ISSUE TITLE
Update PyPi package and homepage

### ISSUE THREAD

**Issue by supermitch** [pycontribs/confluence#36]
I saw the PyPi page for this project (https://pypi.org/project/confluence/) still points to the bitbucket original repo, which has been deleted. A new PyPi release would be great.

**Comment by ssbarnea** [comment]
Sorry but check https://github.com/pycontribs/confluence/issues/7 - given the number of people willing to takeover maintenance of this project, I would say a new release will never happen. If you are interested into taking over maintenance, fixing CI, this might change. I can provide examples and hints but some legwork is needed.
